import React, { useRef, useState } from "react";
import "./SaveDownload.css";

export default function SaveDownload({ palette, detectedColors }) {
  const exportRef = useRef(null);
  const [loading, setLoading] = useState(null); // "png" | "pdf" | null

  if (!palette?.colors) return null;

  const colorList    = Object.values(palette.colors);
  const detectedList = detectedColors || [];

  const handlePNG = async () => {
    setLoading("png");
    try {
      const { default: html2canvas } = await import("html2canvas");
      const canvas = await html2canvas(exportRef.current, {
        backgroundColor: "#14142b",
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const link = document.createElement("a");
      link.download = `EMCO-SALES-Palette-${palette.name.replace(/\s/g, "-")}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (e) {
      console.error("PNG export failed:", e);
    }
    setLoading(null);
  };

  const handlePDF = async () => {
    setLoading("pdf");
    try {
      const { default: html2canvas } = await import("html2canvas");
      const { jsPDF } = await import("jspdf");
      const canvas    = await html2canvas(exportRef.current, {
        backgroundColor: "#14142b",
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL("image/png");
      const pdf     = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pdfW    = pdf.internal.pageSize.getWidth();
      const ratio   = canvas.height / canvas.width;
      const pdfH    = pdfW * ratio;
      pdf.addImage(imgData, "PNG", 0, 0, pdfW, pdfH);
      pdf.save(`EMCO-SALES-Palette-${palette.name.replace(/\s/g, "-")}.pdf`);
    } catch (e) {
      console.error("PDF export failed:", e);
    }
    setLoading(null);
  };

  return (
    <div className="save-download card" id="save-download">
      <div className="section-header">
        <span className="section-icon">💾</span>
        <div>
          <p className="section-title">Save Your Palette</p>
          <p className="section-desc">Download as PNG or branded PDF</p>
        </div>
      </div>

      {/* Export card (this gets captured) */}
      <div className="palette-export-card" ref={exportRef}>
        <div className="export-header">
          <p className="export-logo">🎨 EMCO SALES</p>
          <p className="export-palette-name">{palette.name}</p>
          <p className="export-tagline">Your Trusted Paint &amp; Color Expert | Asian Paints · Birla Opus</p>
        </div>

        {/* Roles */}
        <div className="export-roles">
          {colorList.map((c, i) => (
            <div key={i} className="export-role-row">
              <div className="export-role-dot" style={{ background: c.hex }} />
              <div className="export-role-info">
                <span className="export-role-name">{c.role}</span>
                <span className="export-role-color">{c.name} · {c.hex}</span>
              </div>
            </div>
          ))}
        </div>

        {/* Swatch circles */}
        <div className="export-swatches">
          {colorList.map((c, i) => (
            <div key={i} className="export-swatch">
              <div className="export-swatch-color" style={{ background: c.hex }} />
              <p className="export-swatch-label">{c.name}</p>
              <p className="export-swatch-hex">{c.hex}</p>
            </div>
          ))}
        </div>

        {detectedList.length > 0 && (
          <div className="export-detected">
            <p className="export-section-title">Detected Room Colors</p>
            <div className="export-detected-row">
              {detectedList.slice(0, 8).map((c, i) => (
                <div key={i} className="export-detected-dot" style={{ background: c.hex }} title={c.hex} />
              ))}
            </div>
          </div>
        )}

        <p className="export-footer">
          Generated by EMCO SALES Color Recommendation System · emco-sales.com · +91 90351 51620
        </p>
      </div>

      {/* Download buttons */}
      <div className="download-btns">
        <button
          className="download-btn png"
          onClick={handlePNG}
          disabled={!!loading}
          id="download-png-btn"
        >
          {loading === "png" ? "⏳ Saving..." : "🖼️ Save as PNG"}
        </button>
        <button
          className="download-btn pdf"
          onClick={handlePDF}
          disabled={!!loading}
          id="download-pdf-btn"
        >
          {loading === "pdf" ? "⏳ Saving..." : "📄 Save as PDF"}
        </button>
      </div>
    </div>
  );
}
